### ISSUE TITLE
Some labels are not bolded

### ISSUE THREAD

**Issue by schayes04** [eclair4151/MinecraftServerStatusWidget#4] opened 2018-07-07 18:27 UTC
"Status" and "Motd" are not bolded on the one online server I have. They are bolded on the offline/unknown servers and the rest of the labels are still bolded

**Comment by eclair4151** [comment] 2018-07-08 15:01
unable to reproduce

**Comment by schayes04** [comment] 2018-07-08 17:04
I think it might be related to when the tableview cells get reused

https://imgur.com/a/H58Geqj

**Comment by eclair4151** [comment] 2018-07-08 20:07
fixed in 05066c762399758fb76d79728fd26a9e4702df91

**Closed by eclair4151** 2018-07-08 20:07 UTC
Labels: bug
