### ISSUE TITLE
Cannot display online players in app but can view it in the widget

### ISSUE THREAD

**Issue by FeikoJoosten** [eclair4151/MinecraftServerStatusWidget#8] opened 2018-07-24 21:49 UTC
When viewing the server status in app, the app informs me that I need to set `enable-query` to true to view the online players. However, viewing the server status using the widget, does allow me to view the online players. I’ve checked with the server owner and he confirmed me that the `enable-query` setting is set to true. 

Example images: http://imgur.com/a/buCwDl1

Running version 1.0.1 on an iPhone X running iOS 11.4. 

Edit: updated the post to more accuratly describe the issue.

**Comment by eclair4151** [comment] 2018-07-24 22:05
Hmm interesting. Taking a look now. Do you by any chance know if the server has enable-query turned on?

**Comment by FeikoJoosten** [comment] 2018-07-24 22:11
As far as I’m aware, the enable-query is disabled on the server. But I can double check with the server owner.

**Comment by FeikoJoosten** [comment] 2018-07-24 22:13
Ah, my bad. The enable query is set to true. Just confirmed with the server owner.

**Comment by FeikoJoosten** [comment] 2018-07-25 09:23
I’ve updated the imgur link to include a screenshot with a player online.

**Comment by eclair4151** [comment] 2018-07-25 12:19
So it looks like a bug in the API i am using: https://api.mcsrvstat.us/1/waifu-technologies.moe
for some reason it is returning that enable-query is turned off on the server, but returning the list of names anyway. I have contacted the API owner to see if i can get some more info on whats going on.

**Comment by eclair4151** [comment] 2018-07-25 12:48
Can you by any chance ask the server owner if in his server.properties list he has
query.port=25565

if not can he add it and if it is set to a different port set it to 25565 and restart the server?
Thanks!

**Comment by DragoonX6** [comment] 2018-07-25 12:50
Server owner here, is that TCP or UDP?

**Comment by eclair4151** [comment] 2018-07-25 12:53
actually both. The server status is pulled over the TCP ping protocol
http://wiki.vg/Protocol

and the user list is pulled over UDP using the query protocol
http://wiki.vg/Query

**Comment by DragoonX6** [comment] 2018-07-25 12:55
Oh, in that case just opening up the UDP side of it in my firewall should do the trick.

**Comment by FeikoJoosten** [comment] 2018-07-25 12:59
That seems to have fixed the issue. An error regarding that would be nice though ;)

**Comment by DragoonX6** [comment] 2018-07-25 13:03
It's pretty hard to accurately determine if something isn't listening on the port, if it's null routed, or just not open in the firewall. For example my firewall is configured to just drop the packet, instead of rejecting it.

The easiest way is to just list multiple possible reasons and let users go over them before having to open a bug report.

**Comment by FeikoJoosten** [comment] 2018-07-25 13:05
That is indeed an option.
But as he was able to still retrieve the player names, while still giving out an error that enable-query needed to be true, it should be needed to showcase the error regarding setting enable-query to true anyway. Simply only look at the array of player names, that should already be sufficient afaik.

**Comment by eclair4151** [comment] 2018-07-25 13:10
Yea this is a bit complicated. Feiko is right. it appears UDP is not actually required to get the list of players. The first thing i am going to do is check the list of players and show them in the app even if query is set to false.     
The problem is for servers that have UDP turned off but have no players on the server. In that state there is no way to know if enable-query is on and UDP is off(Which is fine), or if enable-query is just turned off.      
I think i will update it so that in that case there is no message/error shown unless there are people on the server but we are still unable to get the list of players.

**Comment by eclair4151** [comment] 2018-07-26 13:14
fixed in commit de0332bfc1b3b2bd3ad7a8d3ecb3bdee15c4583c

**Closed by eclair4151** 2018-07-26 13:14 UTC
Labels: bug
